---
title: "Test"
author: "Eric Wu"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r libraries}
Sys.setenv(RETICULATE_PYTHON = "/Users/wue77/AppData/Local/Programs/Python/Python310")

library(reticulate)
library(tidyverse)
```

```{python}
import pandas as pd
import requests
import numpy as np
from bs4 import BeautifulSoup

```

```{python}
url = 'https://www.capfriendly.com/browse/active/2023?stats-season=2023'
data = requests.get(url).text
soup = BeautifulSoup(data, 'html.parser')
# find <div class="r" style="margin:0 4px 0 0">Page 2 of 32</div>
res = soup.find('div', class_='r', style='margin:0 4px 0 0')
pc = int(res.text.split(' ')[-1])

master = []
for page in range(1,pc+1):
    url = 'https://www.capfriendly.com/browse/active/2023?stats-season=2023&pg={}'.format(page)
    table = pd.read_html(url)[0]
    master.append(table)

df = pd.concat(master)

# Transfer R value to python
test = r.df
test
```

```{r}
# Transfer python value to R
df <- py$df

```


