---
title: "Test"
author: "Eric Wu"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r libraries}
#| warning = FALSE,
#| message = FALSE

rm(list = ls()) # Clean environment
library(reticulate)
library(tidyverse)
```

## Data Cleaning Relating to Player Statistics

```{r}
# Read the data
#players <- read.csv("player_data_non_duplicate.csv")
#contract <- read.csv("contracts.csv")
data <- read.csv("Player and contract.csv")
test <- read.csv("Combined_data_non_null.csv")
```

```{r}
# Full join
test <- full_join(contract, players, by = join_by(Name == Player), keep = TRUE, relationship = "many-to-many")
```

```{r}
# Clean the position variable and remove redundant column
test <- data %>%
  separate(
    col = Position,
    into = c("Position 1", "Position 2"),
    sep = ", "
  ) %>%
  select(-Player, -Age.y, -Tm, -Pos) %>%
  rename("Age" = "Age.x")
  
```

```{r}
# Exploration work bench
number <- unique(data$Contract.Type)

one_way <- data %>%
  filter(Way.Clause == "1-way")

two_way <- data %>%
  filter(Way.Clause == "2-way")
```

```{r}
# Output file
write.csv(test,"C:\\Users\\wue77\\Documents\\GitHub\\DS-320_Project\\Combined Contract and Player Data\\tests.csv", row.names = FALSE)
```

## Data Visualization

```{r}

```

## Team Data

n: The number of distinct players that were in the team
year: The most recent year (Whether a team disband or not)

```{r}
team <- test %>%
  group_by(Tm) %>%
  summarise(
    n = length(unique(Player)),
    year = max(Year),
    GP = sum(GP),
    G = sum(G),
    A = sum(A),
    PTS = sum(PTS),
    PIM = sum(PIM),
    PS = sum(PS),
    EV = sum(EV),
    PP = sum(PP),
    SH = sum(SH),
    GW = sum(GW),
    EV.1 = sum(EV.1),
    PP.1 = sum(PP.1),
    SH.1 = sum(SH.1),
    S = sum(S),
    S. = sum(S.),
    TOI = sum(TOI),
    ATOI = sum(ATOI),
    BLK = sum(BLK),
    HIT = sum(HIT),
    FOW = sum(FOW),
    FOL = sum(FOL),
    FO. = sum(FO.)
  )

```

```{r}
# Output file
write.csv(team,"C:\\Users\\wue77\\Documents\\GitHub\\DS-320_Project\\Combined Contract and Player Data\\team.csv", row.names = FALSE)
```

```{r}
library(esquisse)
data <- read.csv("Player and contract.csv")
```

```{r}
esquisse::esquisser(data)
```


